# Este archivo evita el error 404
# La configuración real está en el JavaScript de las páginas admin
backend:
  name: test-repo

local_backend: true
media_folder: "public/images/uploads"
public_folder: "/images/uploads"

collections:
  - name: "blog"
    label: "Posts del Blog"
    folder: "src/content/blog"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    fields:
      - {label: "Título", name: "title", widget: "string"}
      - {label: "Descripción", name: "description", widget: "string"}
      - {label: "Fecha de publicación", name: "pubDate", widget: "datetime"}
      - {label: "Contenido", name: "body", widget: "markdown"}
