backend:
  name: github
  repo: facuvar/wallu-resources
  branch: main
  base_url: https://resources.wallu.app
  auth_endpoint: api/oauth

media_folder: "public/images/uploads"
public_folder: "/images/uploads"

collections:
  - name: "blog"
    label: "Posts del Blog"
    folder: "src/content/blog"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    fields:
      - {label: "Título", name: "title", widget: "string"}
      - {label: "Descripción", name: "description", widget: "string"}
      - {label: "Fecha de publicación", name: "pubDate", widget: "datetime"}
      - {label: "Fecha de actualización", name: "updatedDate", widget: "datetime", required: false}
      - {label: "Imagen destacada", name: "heroImage", widget: "image", required: false}
      - {label: "Contenido", name: "body", widget: "markdown"}
