backend:
  name: github
  repo: facuvar/wallu-resources
  branch: main

# Para desarrollo local
local_backend: true

# Configuración adicional para desarrollo
development_overrides:
  backend:
    name: proxy
    proxy_url: http://localhost:8081/api/v1

media_folder: "public/images/uploads" # Carpeta donde se guardarán las imágenes
public_folder: "/images/uploads" # URL pública de las imágenes

collections:
  - name: "blog" # Usado en rutas, ej.: /admin/collections/blog
    label: "Posts del Blog" # Usado en la UI
    folder: "src/content/blog" # Directorio donde están los archivos markdown
    create: true # Permite crear nuevos posts
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}" # Formato del nombre del archivo
    fields: # Los campos de cada post
      - {label: "Título", name: "title", widget: "string"}
      - {label: "Descripción", name: "description", widget: "string"}
      - {label: "Fecha de publicación", name: "pubDate", widget: "datetime"}
      - {label: "Fecha de actualización", name: "updatedDate", widget: "datetime", required: false}
      - {label: "Imagen destacada", name: "heroImage", widget: "image", required: false}
      - {label: "Contenido", name: "body", widget: "markdown"}

  - name: "config"
    label: "Configuración del sitio"
    files:
      - label: "Información general"
        name: "general"
        file: "src/config/site.json"
        fields:
          - {label: "Título del sitio", name: "title", widget: "string"}
          - {label: "Descripción", name: "description", widget: "text"}
          - {label: "URL del sitio", name: "url", widget: "string"}
          - {label: "Email de contacto", name: "email", widget: "string"}
          - {label: "Redes sociales", name: "social", widget: "object", fields: [
              {label: "Twitter", name: "twitter", widget: "string", required: false},
              {label: "Facebook", name: "facebook", widget: "string", required: false},
              {label: "Instagram", name: "instagram", widget: "string", required: false}
            ]}
